In [41]:
from os import cpu_count
from qiskit_aer import AerSimulator
from qiskit import*
from tqdm import tqdm
import pylatexenc
from matplotlib import pyplot as plt
from matplotlib.ticker import FormatStrFormatter,MultipleLocator,LinearLocator
from matplotlib import cm
import numpy as np
from numpy import pi,sin,cos
from numpy.random import randint,choice
from qiskit.quantum_info import Statevector
from multiprocessing import Pool
from datetime import datetime
from sklearn.metrics import r2_score as r2

In [3]:
def parallel(vector:list,func):
    with Pool(int(cpu_count())) as p:
        return p.map(func,vector)

## Quantum Circuits Functions

In [ ]:
def circuit_singlet_creator(angle_between_analyzers:float):
    """
        ----------------------------------------------
        ----- REMEBER TO MODIFY THIS ALPHA VALUE -----
        ----------------------------------------------
    """
    global_shift = 1*pi/2 # alpha angle between analizer 0 and 1 for alice, angle between x and analizer 0 for bob
    # ---------------------------------------
    q = QuantumCircuit(2,2)
    q.x(0); q.x(1); q.h(0); q.rz(relative_phase,0); q.cx(0,1) # singlet state with phase
    q.barrier()
    basis_alice = choice([0,1,2]); basis_bob = choice([1,2,3])
    basis_list = {0:0,1:global_shift,2:(global_shift+angle_between_analyzers),3:3*pi/4}
    q.ry(basis_list[basis_alice],0); q.ry(basis_list[basis_bob],1)
    q.barrier()
    q.measure(0,0); q.measure(1,1)
    basis = str(basis_alice)+str(basis_bob)
    return q,basis
    

In [5]:
def circuit_list_vector_creator(n_states:int,angle_between_analyzers:float):
    circs_basis_vector = parallel([angle_between_analyzers for k in range(n_states)],circuit_singlet_creator)
    return circs_basis_vector

In [6]:
def exec(q:QuantumCircuit):
    simulator = AerSimulator()
    circ = transpile(q, simulator)
    result = simulator.run(circ,shots=1).result().get_counts()
    return list(dict(result).keys())[0]

## Post Execution Functions

In [7]:
def info_selector(circs_basis_vector:list):
    N = len(circs_basis_vector)
    circuits = list()
    basis=list()
    for k in range(N):
        circuits.append(circs_basis_vector[k][0])
        basis.append(circs_basis_vector[k][1])
    return [circuits,basis]

def probability_computation(basis_vector:list,result_vector:list):
    N_same_basis = 0
    N_anticorrelation = 0
    N_states = len(basis_vector)
    for k in range(N_states):
        if basis_vector[k] == '11' or basis_vector[k] == '22':
            N_same_basis += 1
            if result_vector[k] == '10' or result_vector[k] == '01':
                N_anticorrelation += 1
            else:
                pass
        else:
            pass
    return N_anticorrelation/N_same_basis

## Run Function

In [8]:
def local_run (n_states:int,angle_1_2:float):
    info = circuit_list_vector_creator(n_states=n_states,angle_between_analyzers=angle_1_2)
    circuit_list, basis_list = info_selector(info)
    del info
    result = parallel(vector=circuit_list,func=exec)
    result = [result[k]for k in range(len(result))]
    del circuit_list
    fidelity = probability_computation(basis_vector=basis_list,result_vector=result)    
    return fidelity

## plots

In [9]:
def plots (x:list,y_set:list,n_states:int,n_execs:int,relative_phase_set:list):
    f,ax=plt.subplots(1)
    n_y = len(y_set)
    for k in range(n_y):
        phase = round(relative_phase_set[k]/pi,1)
        ax.plot(x/pi,y_set[k],label=f"$\\phi$ = {phase}$\\pi$")
        ax.legend(bbox_to_anchor=(1.3, 1),fancybox=True,title="relative phase $\\phi$")
    ax.set_ylim([0,1.5])
    ax.set_xlim([min(x/pi),max(x/pi)])
    ax.xaxis.set_major_formatter(FormatStrFormatter('%g $\\pi$'))
    ax.xaxis.set_major_locator(MultipleLocator(base=1.0))
    ax.set_xlabel("angle between coincident analyzers",fontsize=12)
    ax.set_ylabel("N_anticorrelations/N_same_basis",fontsize=12)
    plt.title(f"number of states transmitted = {n_states:1.0e}\nnumber of E91 runs = {n_execs}",fontsize=12)
    
    plt.show()

# Analytical Model

In [43]:
def analytical(theta:float,beta:float,alpha:float):
    return (\
        cos(alpha)**4 + sin(alpha)**4 +\
        2 * (sin(alpha)**2) * (cos(alpha)**2) * cos(theta) + \
        cos(alpha+beta)**4 + sin(alpha+beta)**4 + \
        2 * (sin(alpha+beta)**2) * (cos(alpha+beta)**2) * cos(theta)\
        )/2  

In [50]:
def correlation_computing(n_execs:int,n_phase:int,experiment:np.ndarray):
    theta = np.linspace(0,2*pi,n_phase)
    beta = np.linspace(0,2*pi,n_execs)
    """
        ----------------------------------------------
        ----- REMEBER TO MODIFY THIS ALPHA VALUE -----
        ----------------------------------------------
    """
    alpha = pi/2 
    
    theoretical = np.array([[analytical(theta=t,beta=b, alpha=alpha) for t in theta] for b in beta])
    
    print(f"theoretical = ↓\n{theoretical}\n\nexperimental = ↓\n{experiment}")

    return  r2(y_true=theoretical,y_pred=experiment)
    

In [54]:
correlation_computing(4,4,experiment)

theoretical = ↓
[[1.      1.      1.      1.     ]
 [1.      0.71875 0.71875 1.     ]
 [1.      0.71875 0.71875 1.     ]
 [1.      1.      1.      1.     ]]

experimental = ↓
[[1.         1.         1.         1.        ]
 [0.18823529 0.49425287 0.4        0.23255814]
 [0.27058824 0.43529412 0.52873563 0.2       ]
 [1.         1.         1.         1.        ]]


-0.34844474309658996

In [55]:
def run_for_stats(n_states:int,n_execs:int,n_repetitions:int):
    qubit_efficiency = np.zeros(shape=(n_repetitions))
    for repetition in range(n_repetitions):
        #main(n_states,n_execs)


SyntaxError: incomplete input (3343316713.py, line 4)

In [53]:
experiment = np.array([
[0.0,1.0,1.0,1.0,1.0],
[2.0943951023931953,0.18823529411764706,0.4942528735632184,0.4,0.23255813953488372],
[4.1887902047863905,0.27058823529411763,0.43529411764705883,0.5287356321839081,0.2],
[6.283185307179586,1.0,1.0,1.0,1.0],
])


print (experiment)
print("\n\n")

theta = np.linspace(0,2*pi,4)
beta = np.linspace(0,2*pi,4)
alpha = pi/2
experiment = experiment[0:,1:]
print (experiment)

[[0.         1.         1.         1.         1.        ]
 [2.0943951  0.18823529 0.49425287 0.4        0.23255814]
 [4.1887902  0.27058824 0.43529412 0.52873563 0.2       ]
 [6.28318531 1.         1.         1.         1.        ]]



[[1.         1.         1.         1.        ]
 [0.18823529 0.49425287 0.4        0.23255814]
 [0.27058824 0.43529412 0.52873563 0.2       ]
 [1.         1.         1.         1.        ]]


# main 

In [25]:
def main(n_states:int,n_execs:int):
    fidelity = list()
    for k in range(n_execs):
        fidelity.append(local_run(n_states=n_states,angle_1_2=angle_between_analyzers[k]))
    return np.array(fidelity)
    
def save_info_to_csv(column:list,backend_name,time_str):
    file_name = f"E91_data_{backend_name}_{time_str}.csv"
    string = f"{column[0]}"
    for data in column[1]:
        string += f",{data}"
    with open(file_name, "a") as file:
        file.write(string + "\n")

In [52]:
states = int(400) # total states created by the source in the QKD Run 
execs = int(4) # steps of angle between oincident analyzers beta parameter between 0 and 2 pi
n_phase = int(4) # steps of FSS parameter theta between 0 and 2 pi

phase = np.linspace(0,2*pi,n_phase)

global angle_between_analyzers
angle_between_analyzers = np.linspace(0,2*pi,execs)

time_now = datetime.now().strftime("%d_%m_%Y_%H_%M_%S")

for rel_phase in tqdm(phase,desc="progress: "):
    global relative_phase
    relative_phase=rel_phase # phase between bell pair state
    #---------------------------------------------------
    out = main(n_states=states,n_execs=execs)
    if rel_phase != 0.:
        save_info_to_csv(column=[rel_phase,out],backend_name="aer_simulator",time_str=time_now)
    else:
        save_info_to_csv(column=['#',angle_between_analyzers],backend_name="aer_simulator",time_str=time_now)
        save_info_to_csv(column=[rel_phase,out],backend_name="aer_simulator",time_str=time_now)
    #---------------------------------------------------

progress: 100%|██████████| 4/4 [03:09<00:00, 47.45s/it]


# Plots

In [ ]:
time_now

'24_06_2024_11_09_18'

In [ ]:
plots(x=angle,y_set=result,n_states=states,n_execs=execs,relative_phase_set=phase)


NameError: name 'angle' is not defined

In [ ]:
fg = plt.figure(figsize=(8,8))
plt.imshow(result, cmap='Blues', interpolation='nearest')
plt.colorbar()
plt.contour(result)

plt.show()

In [ ]:
X,Y = np.meshgrid(angle/pi,phase/pi)
f,axs = plt.subplots(subplot_kw={'projection':'3d'},figsize=(8,8))
surf = axs.plot_surface(X,Y,np.array(result),cmap=cm.magma)
axs.set_xlabel("Angle between polarizers",fontsize=12)
axs.set_ylabel("Relative Phase of Bell State",fontsize=12)
axs.set_zlabel("N_anticorrelations/N_same_basis",fontsize=12)
axs.set_zlim([0,1.3])
axs.xaxis.set_major_formatter(FormatStrFormatter('%g $\\pi$'))
axs.xaxis.set_major_locator(MultipleLocator(base=1.0))
axs.yaxis.set_major_formatter(FormatStrFormatter('%g $\\pi$'))
axs.yaxis.set_major_locator(MultipleLocator(base=1.0))
f.colorbar(surf, shrink=0.5, aspect=5)
plt.show()